### ISSUE TITLE
Automaticly highlight everything until newline found, if not specified.

### ISSUE THREAD

**Issue by FilipAndersson245** [zimonitrome/vscode-color-blocks#3]
I think it would be nice if you were not required to specify the number of lines, instead of inferring until an empty line is found.
![image](https://user-images.githubusercontent.com/17986183/163669841-91ea992d-c131-4c27-ad58-095466c0894e.png)
![image](https://user-images.githubusercontent.com/17986183/163669932-2604037a-54da-45c0-9370-cf2a31ea3a06.png)
So these two would produce the same result.

**Comment by zimonitrome** [comment]
Good suggestion. This is being worked on here: https://github.com/zimonitrome/vscode-color-blocks/tree/improvecomments

This will probably also cause some change in how the color blocks are used currently so expect a major release soon :)
