### ISSUE TITLE
Highlighting desync sometimes

### ISSUE THREAD

**Issue by FilipAndersson245** [zimonitrome/vscode-color-blocks#4]
![image](https://user-images.githubusercontent.com/17986183/163670099-b63925f7-1aea-4332-80ef-4c9e6f9c9a95.png)
Highlighting seems to sometime not update correctly when adding newlines.

**Comment by zimonitrome** [comment]
I have also noticed this at times. It almost seems like the entire extension crashes...

Would be nice to find a way to reliably reproduce this. Will explore further.
